import { UI_THEME_CSS } from './ui-theme.js';

export function authPage(setup: boolean, local: boolean, requiresEmail = true): string {
  return `<!doctype html><html data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${setup ? 'Create account' : 'Sign in to'} Agent Gitu</title><style>${UI_THEME_CSS}
*{box-sizing:border-box}body{margin:0;min-height:100dvh;display:grid;place-items:center;background:var(--bg);color:var(--text);font:15px/1.6 system-ui,sans-serif;padding:24px}.auth{width:100%;max-width:420px}.brand{color:var(--accent);font-weight:650;margin:0 0 32px}h1{font-size:30px;line-height:1.2;letter-spacing:-.03em;margin:0 0 12px}.hint{color:var(--muted);margin:0 0 26px}label{display:block;margin:18px 0 6px;font-weight:600;font-size:13px}input{width:100%;border:1px solid var(--border2);border-radius:10px;padding:12px 14px;font:inherit;background:var(--card);color:var(--text)}input:focus{outline:2px solid var(--accent);outline-offset:2px}button{width:100%;margin-top:24px;border:0;border-radius:10px;padding:12px;background:var(--accent);color:var(--on-accent);font:600 15px system-ui;cursor:pointer}button:disabled{opacity:.6;cursor:wait}.error{color:var(--err);margin-top:14px;font-size:14px}.note{font-size:12px;color:var(--muted);margin-top:20px}
</style></head><body><main class="auth"><p class="brand">Agent Gitu</p><h1>${setup ? 'Create your account' : 'Welcome back'}</h1><p class="hint">${setup ? (local ? 'Register as the workspace owner to protect your chats, files, and connected accounts.' : 'Create the first account on the computer running Agent Gitu, then return here to sign in.') : 'Sign in to unlock your Agent Gitu workspace.'}</p>${!setup || local ? `<form id="authForm">${setup ? '<label for="name">Your name</label><input id="name" name="name" type="text" autocomplete="name" maxlength="100" required autofocus>' : ''}${setup || requiresEmail ? '<label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="username" maxlength="254" required>' : ''}<label for="password">${setup ? 'Create password' : 'Password'}</label><input id="password" name="password" type="password" autocomplete="${setup ? 'new-password' : 'current-password'}" ${setup ? 'minlength="15"' : ''} maxlength="256" required ${setup ? '' : 'autofocus'}>${setup ? '<label for="confirm">Confirm password</label><input id="confirm" type="password" autocomplete="new-password" minlength="15" maxlength="256" required>' : ''}<p class="error" role="alert" id="error" hidden></p><button id="submit" type="submit">${setup ? 'Create account' : 'Sign in'}</button></form><p class="note">${setup ? 'Use a long, unique passphrase of at least 15 characters. Store it in your password manager.' : 'Your session expires after 8 hours. You can lock the app from Cowork.'}</p>` : ''}</main><script>
const form = document.getElementById('authForm');
if(form) form.onsubmit = async event => {
  event.preventDefault(); const password = document.getElementById('password'); const button = document.getElementById('submit'); const error = document.getElementById('error'); error.hidden = true;
  ${setup ? "if(password.value !== document.getElementById('confirm').value){error.textContent='The passwords do not match.';error.hidden=false;return;}" : ''}
  button.disabled=true;
  try{const response=await fetch('/api/auth/${setup ? 'register' : 'login'}',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:password.value,${setup ? 'name:document.getElementById("name").value,' : ''}${setup || requiresEmail ? 'email:document.getElementById("email").value' : ''}})});const data=await response.json();if(!response.ok)throw new Error(data.error || 'Could not unlock the app.');password.value='';location.replace('${setup ? '/auth' : '/'}');}catch(e){error.textContent=e.message;error.hidden=false;button.disabled=false;}
};
</script></body></html>`;
}
